name: Run Parser Twice A Week

on:
  schedule:
    - cron: '0 4 * * 1,4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run parser
      run: python parser.py

    - name: Upload result file
      uses: actions/upload-artifact@v4
      with:
        name: mot-o_final
        path: mot-o_final.xml
    - name: Upload XML to Google Drive
      uses: gautamkrishnar/google-drive-upload-git-action@v1.2.0
      with:
        credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        folderId: ПІДСТАВ_СВІЙ_FOLDER_ID
        target: mot-o_final.xml
